# Generated by Django 4.1.6 on 2023-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_remove_trip_dates_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='trip_currency',
        ),
        migrations.AddField(
            model_name='budget',
            name='purpose',
            field=models.CharField(choices=[('food', 'FOOD'), ('transportation', 'TRANSPORTATION'), ('entertainment', 'ENTERTAINMENT'), ('other', 'OTHER')], default='other', max_length=30),
        ),
    ]
