# Generated by Django 4.1.6 on 2023-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_remove_budget_trip_currency_budget_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='purpose',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Transportation', 'TRANSPORTATION'), ('Entertainment', 'ENTERTAINMENT'), ('Other', 'OTHER')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD')], default='USD', max_length=3),
        ),
    ]
